### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by IvViral** [DennisRas/WeeklyKnowledge#1]
Message: Interface/AddOns/WeeklyKnowledge/Core.lua:1: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceBucket-3.0".
Time: Tue Aug 27 15:43:05 2024
Count: 1
Stack: Interface/AddOns/WeeklyKnowledge/Core.lua:1: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceBucket-3.0".
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:185: in function `EmbedLibrary'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:167: in function `EmbedLibraries'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:134: in function `NewAddon'
[string "@Interface/AddOns/WeeklyKnowledge/Core.lua"]:1: in main chunk

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "WeeklyKnowledge"
 orderedModules = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
libname = "AceBucket-3.0"
silent = false
offset = 4
lib = nil

**Comment by DennisRas** [comment]
@IvViral Thank you!
I'll have a fix updated in a minute.
