### ISSUE TITLE
Option to disable minimap icon or disable minimap icon when ldb is used

### ISSUE THREAD

**Issue by Thaodan** [DennisRas/WeeklyKnowledge#15]
It would be great if there was an option to disable the minimap icon or to disable it by default when a ldb shortcut exists.

**Comment by DennisRas** [comment]
Hey there :-)

Thanks for the feedback.
There's already a chat command to toggle the minimal, however it's pretty hidden and only shown in the readme description. I'm adding a settings menu this weekend and will add the option there.

Could you clarify "ldb shortcut" ?

**Comment by Thaodan** [comment]
I was looking for information how to make the slash commands better visible while you already replied.

I found the option after reading your code.

If you would use AceConfigCmd instead of parsing the arguments your self it would be easier to discover the option since then there's a help option to show all the valid arguments to your commands.

**Comment by Thaodan** [comment]
By LDP shortcut I mean, if the user already uses a LDB shortcut in a addon which displays data brokers the  minimap icon is redundant.

**Comment by DennisRas** [comment]
> I was looking for information how to make the slash commands better visible while you already replied.
> 
> I found the option after reading your code.
> 
> If you would use AceConfigCmd instead of parsing the arguments your self it would be easier to discover the option since then there's a help option to show all the valid arguments to your commands.

That's true. I did that yesterday but scratched it because it wouldn't have a default command for toggling the main window if you didn't use any arguments. Or at least from what I could come up with.

Using the Cmd handler /wk would just show the options/arguments rather than having a main callback handler. If there's a way then I'll add it back in :-)

**Comment by DennisRas** [comment]
> By LDP shortcut I mean, if the user already uses a LDB shortcut in a addon which displays data brokers the  minimap icon is redundant.

I see. I was sure that was the default behavior from data broker display addons.

**Comment by Thaodan** [comment]
> > By LDP shortcut I mean, if the user already uses a LDB shortcut in a addon which displays data brokers the  minimap icon is redundant.
> 
> I see. I was sure that was the default behavior from data broker display addons.

The databroker addon doesn't decide on the minimap icon I think, it's the addon that provides the broker.

**Comment by DennisRas** [comment]
I'll let the user decide with a new visible setting :-) Best of both worlds and takes a minute for the user to decide once.
Sometimes people do want a minimap icon as well even if they have a data broker display addon.

**Comment by DennisRas** [comment]
This has been added in v1.0.3
