### ISSUE TITLE
Toggle character professions

### ISSUE THREAD

**Issue by DennisRas** [DennisRas/WeeklyKnowledge#22]
Suggested on CurseForge:

> Hi, great work you're doing, I'm really loving the addon. I'd like to suggest a new feature that is being able to hide a specific profession from a specific character. There are some characters that i have both professions but i don't wanna track both of them. Thanks again.

**Comment by KatyPurry** [comment]
I agree ! I have a tons of Alts but I don't want leveling all professions :D

**Comment by DennisRas** [comment]
> I agree ! I have a tons of Alts but I don't want leveling all professions :D

As soon as I get rid of the bugs I'll get on it :-)
Thank you for providing feedback.
