### ISSUE TITLE
Adjust scrolling distance

### ISSUE THREAD

**Issue by DennisRas** [DennisRas/WeeklyKnowledge#42]
**Issue:**
Now that lists are getting longer, the current scrollbar jumps a lot of lines/rows as it's currently set to scroll a fixed 20% per delta/wheel.

**Solution:**
Change the delta to a fixed height of X rows (maybe 5).
Remember to add a new calculation for the length of the scrollbar thumb

**Comment by Numynum** [comment]
I felt like 5 is rather a lot, and was looking at other apps to see what kind of scroll distance they use
seems quite some use 3 lines per tick; discord uses 5, though that doesn't feel as bad, as it's a smoothed out scroll, as opposed to a solid snap (which I wouldn't recommend trying to make happen in wow, smoothing out scrolls is lotsa effort for little reward 🙈 )
for me personally, with harsh snaps, smaller = better, it helps keep better track of the row I was looking at, which to me is more important than being able to jump straight down to the bottom of the list ^^

just some thoughts ^^

**Comment by DennisRas** [comment]
I agree @Numynum  
I'll get it implemented and test it out with 3.

**Comment by DennisRas** [comment]
Decided to go with 2 rows.

https://github.com/user-attachments/assets/14f5bc1a-d407-4813-90e0-86d9584f2a66
