### ISSUE TITLE
Invisible character on character list

### ISSUE THREAD

**Issue by KatyPurry** [DennisRas/WeeklyKnowledge#47]
Hello,

I installed the last version (1.1.3) and I have a ghost character in the list:

![image](https://github.com/user-attachments/assets/21e7de72-a3aa-41fc-b185-d737ae323c4a)

I don't know what's causing it.

**Comment by DennisRas** [comment]
Hey there Katy!
That is indeed odd.
Do you also have a ghost character shown on the main table grid?
In any case, would you be able to provide your WeeklyKnowledge savedvariables (`_retail_/WTF/<account>/SavedVariables/WeeklyKnowledge.lua`), so I can investigate?

**Comment by DennisRas** [comment]
Oh looks like I have it as well hehe.

![image](https://github.com/user-attachments/assets/6cb54f2b-4d86-4232-be29-89d622385e8a)

**Comment by KatyPurry** [comment]
So it looks like it was the last update that brought this bonus character, haha.

**Comment by DennisRas** [comment]
At least nothing else is broken right? :)
Basically just an empty option. I'll investigate tomorrow if it's not critical.

**Comment by KatyPurry** [comment]
Nothing seems broken, not a critical bug :D

**Comment by DennisRas** [comment]
Alright phew, because I am BEAT today.
Will take a look into it tomorrow :)
Thanks for reporting.

**Comment by DennisRas** [comment]
Should be fixed in https://github.com/DennisRas/WeeklyKnowledge/commit/26f72de0841933843f13bbeeb8e5f7482ae906aa

**Comment by KatyPurry** [comment]
Unfortunately, this seems to be always present

![image](https://github.com/user-attachments/assets/db0561fa-118a-4780-a205-83d03c39047e)

**Comment by DennisRas** [comment]
Hi @KatyPurry 
Have you updated to the latest verison? Just checking of course.
Because the latest version should have profession checkboxes too and I don't see those (although if those lines are truly black, then there may not be professions for those anyway)

**Comment by KatyPurry** [comment]
Yes I'm on v1.1.5

**Comment by DennisRas** [comment]
Would you be able to provide your SavedVariables file? Do you know which file it is and where it's located?
Something in it is not being cleared.

**Comment by DennisRas** [comment]
Thank you.
I've saved it and will take a look.

**Comment by KatyPurry** [comment]
Any update ? It's getting out of hand :D
![image](https://github.com/user-attachments/assets/e69c1ca4-52d5-49e3-9d1b-69d1a8944ecc)

**Comment by DennisRas** [comment]
What the heck haha 😂
I've been very busy these days with raiding, work and some other AddOns.
Do you reckon those are lower level alts?

**Comment by KatyPurry** [comment]
All my characters are from 70 to 80
