### ISSUE TITLE
Knowledge points column calculation problem

### ISSUE THREAD

**Issue by will0w7** [DennisRas/WeeklyKnowledge#51]
Hey!

Looks like the knowledge calculation is not working as expected. Every reload the number vary.

![imagen](https://github.com/user-attachments/assets/bdc8c4d6-0a63-4e1a-bc34-06cbd68eabe7)

Next reload:

![imagen](https://github.com/user-attachments/assets/557fbd5b-c040-40e4-bcb4-929e9c254422)

Next:

![imagen](https://github.com/user-attachments/assets/33d2b662-86c0-446a-aa26-a6473774e659)

It seems that the number is adding up (the first character, Curasao), but I can't tell you for sure how many reloads I did before taking the first screenshot.
I logged in with the other characters (and /reload'ed) possibly multiple times before seeing the error with this character

If you need more info, let me know :)

**Comment by DennisRas** [comment]
Thank you @will0w7 :-)

That is indeed a bug from the last update.
I'll look into it and get a fix sorted asap.
