### ISSUE TITLE
Skill level no longer updates

### ISSUE THREAD

**Issue by KatyPurry** [DennisRas/WeeklyKnowledge#52]
Skill level no longer updates since version v1.1.5

![image](https://github.com/user-attachments/assets/74ec0708-e675-4ea8-8bf9-ee397be80e52)

There's also a problem with the points, but I see it's already been reported here: https://github.com/DennisRas/WeeklyKnowledge/issues/51

**Comment by KatyPurry** [comment]
It could also simply be that my new skill level wasn't updated due to a bug in the update, and it wouldn't have anything to do with racials.

**Comment by DennisRas** [comment]
The skill column isn't really coded for anything more than just `0 - maxSkill` at the moment.

**Comment by KatyPurry** [comment]
> The skill column isn't really coded for anything more than just `0 - maxSkill` at the moment.

Okay, I've just tested with another character and this is the level that hasn't updated since the last update.

**Comment by DennisRas** [comment]
Thank you @KatyPurry :)
I apprecaite you.
Should be fixed in the update coming out now to everyone.
